# Generated by Django 3.0.6 on 2020-05-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='cr_da',
        ),
    ]
